-- Legacy note: this file was used by the old PostgreSQL Docker entrypoint.
-- MySQL deployments apply schema via `apps/scraper` migrations (`db/migrations/*`) at container start.
-- Intentionally empty.
